//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Крутолапов
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingTable
    {
        public string FIOSportsmena { get; set; }
        public string Gender { get; set; }
        public System.DateTime YearOfBirth { get; set; }
        public string FIOTrenera { get; set; }
        public string NazvaniyStran { get; set; }
        public int Rating2017 { get; set; }
        public int Rating2018 { get; set; }
        public int Rating2019 { get; set; }
        public int Rating2020 { get; set; }
        public int Rating2021 { get; set; }
    }
}
